import {useMemo,useState} from 'react';
import {useFormik} from 'formik';
import {useSearchParams} from 'react-router-dom';
import Reveal from '../components/Reveal';
import {contactInfo,services} from '../data';

export default function Contact(){
  const [params]=useSearchParams();const initialService=params.get('service')||'';const [status,setStatus]=useState('');
  const formik=useFormik({initialValues:{name:'',email:'',phone:'',company:'',service:initialService,budget:'',message:''},validate:v=>{const e={};if(v.name.trim().length<2)e.name='Please enter your name.';if(!/^\S+@\S+\.\S+$/.test(v.email))e.email='Enter a valid email.';if(v.phone.replace(/\D/g,'').length<7)e.phone='Enter a valid phone number.';if(!v.service)e.service='Select a service.';if(v.message.trim().length<20)e.message='Please share at least 20 characters.';return e},onSubmit:(v,{setSubmitting})=>{const s=services.find(x=>x.slug===v.service);const msg=[`Hello Vantesla, I would like to discuss a project.`,``,`Name: ${v.name}`,`Email: ${v.email}`,`Phone: ${v.phone}`,`Company: ${v.company||'Not provided'}`,`Service: ${s?.title||v.service}`,`Budget: ${v.budget||'Not specified'}`,``,`Project details:`,v.message].join('\n');setStatus('Your project brief is ready. WhatsApp is opening now.');window.open(`https://wa.me/${contactInfo.phoneHref.replace(/\D/g,'')}?text=${encodeURIComponent(msg)}`,'_blank','noopener,noreferrer');setSubmitting(false)}});
  const selected=useMemo(()=>services.find(s=>s.slug===formik.values.service),[formik.values.service]);const field=name=>formik.touched[name]&&formik.errors[name];
  return <><section className="page-hero page-hero--visual page-hero--contact"><div className="container page-hero-grid"><Reveal><div><span className="eyebrow eyebrow--light">Start a project</span><h1>Tell us what you want to build.</h1><p>Share the essentials. We will review your brief and respond with a practical next step.</p></div></Reveal><Reveal delay={100}><div className="page-hero-image"><img src="https://framerusercontent.com/images/ur3blVQXPBPq71eChMB516I5XrI.jpg?height=4000&width=6000" alt="Professional business project discussion"/></div></Reveal></div></section>
  <section className="section"><div className="container contact-grid"><Reveal><aside><span className="eyebrow">Direct contact</span><h2>Make the first conversation useful.</h2><p>Include your business goal, required service, preferred timeline and any helpful links.</p><div className="contact-cards"><a href={`tel:${contactInfo.phoneHref}`}><span>Phone & WhatsApp</span><strong>{contactInfo.phone}</strong></a><a href={`mailto:${contactInfo.email}`}><span>Email</span><strong>{contactInfo.email}</strong></a><div><span>Location</span><strong>{contactInfo.location}</strong></div></div></aside></Reveal>
  <Reveal delay={90}><form className="contact-form" onSubmit={formik.handleSubmit} noValidate><div className="form-intro"><span>Project enquiry</span><h3>Start with the details</h3></div>{status&&<div className="form-status">{status}</div>}<div className="field-grid"><label><span>Name *</span><input name="name" value={formik.values.name} onChange={formik.handleChange} onBlur={formik.handleBlur} placeholder="Your name"/>{field('name')&&<small>{field('name')}</small>}</label><label><span>Work email *</span><input name="email" type="email" value={formik.values.email} onChange={formik.handleChange} onBlur={formik.handleBlur} placeholder="you@company.com"/>{field('email')&&<small>{field('email')}</small>}</label><label><span>Phone / WhatsApp *</span><input name="phone" value={formik.values.phone} onChange={formik.handleChange} onBlur={formik.handleBlur} placeholder="+1 234 567 890"/>{field('phone')&&<small>{field('phone')}</small>}</label><label><span>Company</span><input name="company" value={formik.values.company} onChange={formik.handleChange} placeholder="Company name"/></label></div><label><span>Service *</span><select name="service" value={formik.values.service} onChange={formik.handleChange} onBlur={formik.handleBlur}><option value="">Select a service</option>{services.map(s=><option key={s.slug} value={s.slug}>{s.title}</option>)}</select>{field('service')&&<small>{field('service')}</small>}</label><label><span>Approximate budget</span><select name="budget" value={formik.values.budget} onChange={formik.handleChange}><option value="">Select a range</option><option>Under $1,000</option><option>$1,000–$3,000</option><option>$3,000–$7,500</option><option>$7,500+</option><option>Not sure yet</option></select></label><label><span>Project details *</span><textarea name="message" rows="7" value={formik.values.message} onChange={formik.handleChange} onBlur={formik.handleBlur} placeholder={selected?`Tell us what you need for ${selected.title}, your timeline and desired outcome.`:'Tell us about the project, your goal, timeline and any useful links.'}/>{field('message')&&<small>{field('message')}</small>}</label><button className="button" type="submit" disabled={formik.isSubmitting}>Send project brief <span>↗</span></button><p className="form-note">Submitting opens your completed enquiry securely in WhatsApp.</p></form></Reveal></div></section></>
}
